#ifndef TCM_ORDINAL_H
#define TCM_ORDINAL_H

#pragma pack(push)
#pragma pack(1)

#include "../include/trousers/tss/tpm_ordinal.h"


//////////////////////////////////////////////////////////////////////////
//
// TCM Command
//
//////////////////////////////////////////////////////////////////////////

#define TCM_PROTECTED_COMMAND                   ((UINT32)0x00000000)
#define TCM_UNPROTECTED_COMMAND                 ((UINT32)0x80000000)
#define TCM_CONNECTION_COMMAND                  ((UINT32)0x40000000)
#define TCM_VENDOR_COMMAND                      ((UINT32)0x20000000))

#define TCM_PROTECTED_ORDINAL                   ((UINT32)0x00008000)

//////////////////////////////////////////////////////////////////////////
// 命令标识
//////////////////////////////////////////////////////////////////////////
#define TCM_TAG_RQU_COMMAND                     ((UINT16)0x00C1)
#define TCM_TAG_RQU_AUTH1_COMMAND               ((UINT16)0x00C2)
#define TCM_TAG_RQU_AUTH2_COMMAND               ((UINT16)0x00C3)
#define TCM_TAG_RSP_COMMAND                     ((UINT16)0x00C4)
#define TCM_TAG_RSP_AUTH1_COMMAND               ((UINT16)0x00C5)
#define TCM_TAG_RSP_AUTH2_COMMAND               ((UINT16)0x00C6)



typedef UINT16              TCM_KEY_USAGE;
#define TCM_SM2KEY_SIGNING                      ((UINT16)0x0010)
#define TCM_SM2KEY_STORAGE                      ((UINT16)0x0011)
#define TCM_SM2KEY_IDENTITY                     ((UINT16)0x0012)
#define TCM_SM2KEY_BIND                         ((UINT16)0x0014)
#define TCM_SM2KEY_MIGRATE                      ((UINT16)0x0016)
#define TCM_SM2KEY_PEK                          ((UINT16)0x0017)
#define TCM_SMS4KEY_STORAGE                     ((UINT16)0x0018)
#define TCM_SMS4KEY_BIND                        ((UINT16)0x0019)
#define TCM_SMS4KEY_MIGRATE                     ((UINT16)0x001A)

//////////////////////////////////////////////////////////////////////////
// TCM命令
//////////////////////////////////////////////////////////////////////////
#define TCM_ORD_ChangeAuth                      (TCM_PROTECTED_ORDINAL + 0x0C)
#define TCM_ORD_TakeOwnership                   (TCM_PROTECTED_ORDINAL + 0x0D)
#define TCM_ORD_ChangeAuthOwner                 (TCM_PROTECTED_ORDINAL + 0x10)
#define TCM_ORD_Extend                          (TCM_PROTECTED_ORDINAL + 0x14)
#define TCM_ORD_PcrRead                         (TCM_PROTECTED_ORDINAL + 0x15)
#define TCM_ORD_Quote                           (TCM_PROTECTED_ORDINAL + 0x16)
#define TCM_ORD_Seal                            (TCM_PROTECTED_ORDINAL + 0x17)
#define TCM_ORD_Unseal                          (TCM_PROTECTED_ORDINAL + 0x18)
#define TCM_ORD_CreateWrapKey                   (TCM_PROTECTED_ORDINAL + 0x1F)
#define TCM_ORD_CertifyKey                      (TCM_PROTECTED_ORDINAL + 0x32)
#define TCM_ORD_Sign                            (TCM_PROTECTED_ORDINAL + 0x3C)
#define TCM_ORD_SetCapability                   (TCM_PROTECTED_ORDINAL + 0x3F)
#define TCM_ORD_ResetLockValue                  (TCM_PROTECTED_ORDINAL + 0x40)
#define TCM_ORD_GetRandom                       (TCM_PROTECTED_ORDINAL + 0x46)
#define TCM_ORD_SelfTestFull                    (TCM_PROTECTED_ORDINAL + 0x50)
#define TCM_ORD_ContinueSelfTest                (TCM_PROTECTED_ORDINAL + 0x53)
#define TCM_ORD_GetTestResult                   (TCM_PROTECTED_ORDINAL + 0x54)
#define TCM_ORD_OwnerClear                      (TCM_PROTECTED_ORDINAL + 0x5B)
#define TCM_ORD_DisableOwnerClear               (TCM_PROTECTED_ORDINAL + 0x5C)
#define TCM_ORD_ForceClear                      (TCM_PROTECTED_ORDINAL + 0x5D)
#define TCM_ORD_DisableForceClear               (TCM_PROTECTED_ORDINAL + 0x5E)
#define TCM_ORD_GetCapability                   (TCM_PROTECTED_ORDINAL + 0x65)
#define TCM_ORD_OwnerSetDisable                 (TCM_PROTECTED_ORDINAL + 0x6E)
#define TCM_ORD_PhysicalEnable                  (TCM_PROTECTED_ORDINAL + 0x6F)
#define TCM_ORD_PhysicalDisable                 (TCM_PROTECTED_ORDINAL + 0x70)
#define TCM_ORD_SetOwnerInstall                 (TCM_PROTECTED_ORDINAL + 0x71)
#define TCM_ORD_PhysicalSetDeactivated          (TCM_PROTECTED_ORDINAL + 0x72)
#define TCM_ORD_SetTempDeactivated              (TCM_PROTECTED_ORDINAL + 0x73)
#define TCM_ORD_SetOperatorAuth                 (TCM_PROTECTED_ORDINAL + 0x74)
#define TCM_ORD_CreateEndorsementKeyPair        (TCM_PROTECTED_ORDINAL + 0x78)
#define TCM_ORD_MakeIdentity                    (TCM_PROTECTED_ORDINAL + 0x79)
#define TCM_ORD_ActivateIdentity                (TCM_PROTECTED_ORDINAL + 0x7A)
#define TCM_ORD_ReadPubek                       (TCM_PROTECTED_ORDINAL + 0x7C)
#define TCM_ORD_CreateRevocableEK               (TCM_PROTECTED_ORDINAL + 0x7F)
#define TCM_ORD_RevokeTrust                     (TCM_PROTECTED_ORDINAL + 0x80)
#define TCM_ORD_OwnerReadInternalPub            (TCM_PROTECTED_ORDINAL + 0x81)
#define TCM_ORD_GetAuditDigest                  (TCM_PROTECTED_ORDINAL + 0x85)
#define TCM_ORD_GetAuditDigestSigned            (TCM_PROTECTED_ORDINAL + 0x86)
#define TCM_ORD_SetOrdinalAuditStatus           (TCM_PROTECTED_ORDINAL + 0x8D)
#define TCM_ORD_SaveState                       (TCM_PROTECTED_ORDINAL + 0x98)
#define TCM_ORD_Startup                         (TCM_PROTECTED_ORDINAL + 0x99)
#define TCM_ORD_FieldUpgrade                    (TCM_PROTECTED_ORDINAL + 0xAA)
#define TCM_ORD_SaveContext                     (TCM_PROTECTED_ORDINAL + 0xB8)
#define TCM_ORD_LoadContext                     (TCM_PROTECTED_ORDINAL + 0xB9)
#define TCM_ORD_FlushSpecific                   (TCM_PROTECTED_ORDINAL + 0xBA)
#define TCM_ORD_APCreate                        (TCM_PROTECTED_ORDINAL + 0xBF)
#define TCM_ORD_APTerminate                     (TCM_PROTECTED_ORDINAL + 0xC0)
#define TCM_ORD_CreateMigratedBlob              (TCM_PROTECTED_ORDINAL + 0xC1)
#define TCM_ORD_ConvertMigrationBlob            (TCM_PROTECTED_ORDINAL + 0xC2)
#define TCM_ORD_AuthorizeMigrationKey           (TCM_PROTECTED_ORDINAL + 0xC3)
#define TCM_ORD_SMS4Encrypt                     (TCM_PROTECTED_ORDINAL + 0xC5)
#define TCM_ORD_SMS4Decrypt                     (TCM_PROTECTED_ORDINAL + 0xC6)
#define TCM_ORD_PCR_Reset                       (TCM_PROTECTED_ORDINAL + 0xC8)
#define TCM_ORD_NV_DefineSpace                  (TCM_PROTECTED_ORDINAL + 0xCC)
#define TCM_ORD_NV_WriteValue                   (TCM_PROTECTED_ORDINAL + 0xCD)
#define TCM_ORD_NV_WriteValueAuth               (TCM_PROTECTED_ORDINAL + 0xCE)
#define TCM_ORD_NV_ReadValue                    (TCM_PROTECTED_ORDINAL + 0xCF)
#define TCM_ORD_NV_ReadValueAuth                (TCM_PROTECTED_ORDINAL + 0xD0)
#define TCM_ORD_ActivatePEK                     (TCM_PROTECTED_ORDINAL + 0xD9)
#define TCM_ORD_ActivatePEKCert                 (TCM_PROTECTED_ORDINAL + 0xDA)
#define TCM_ORD_CreateCounter                   (TCM_PROTECTED_ORDINAL + 0xDC)
#define TCM_ORD_IncrementCounter                (TCM_PROTECTED_ORDINAL + 0xDD)
#define TCM_ORD_ReadCounter                     (TCM_PROTECTED_ORDINAL + 0xDE)
#define TCM_ORD_ReleaseCounter                  (TCM_PROTECTED_ORDINAL + 0xDF)
#define TCM_ORD_ReleaseCounterOwner             (TCM_PROTECTED_ORDINAL + 0xE0)
#define TCM_ORD_SM3Start                        (TCM_PROTECTED_ORDINAL + 0xEA)
#define TCM_ORD_SM3Update                       (TCM_PROTECTED_ORDINAL + 0xEB)
#define TCM_ORD_SM3Complete                     (TCM_PROTECTED_ORDINAL + 0xEC)
#define TCM_ORD_SM3CompleteExtend               (TCM_PROTECTED_ORDINAL + 0xED)
#define TCM_ORD_SM2Decrypt                      (TCM_PROTECTED_ORDINAL + 0xEE)
#define TCM_ORD_LoadKey                         (TCM_PROTECTED_ORDINAL + 0xEF)
#define TCM_ORD_GetTicks                        (TCM_PROTECTED_ORDINAL + 0xF1)
#define TCM_ORD_TickStampBlob                   (TCM_PROTECTED_ORDINAL + 0xF2)

#define TCM_ORD_PhysicalPresence                (TCM_PROTECTED_ORDINAL + 0x0A)

//add by wangqi 20081121 为与tcm一致添加
// #define TSC_ORD_PhysicalPresence                    (TCM_PROTECTED_ORDINAL+0x0A)
// #define TCM_ORD_ChangeAuth                           (TCM_PROTECTED_ORDINAL + 0x0C)
 #define TCM_ORD_TakeOwnerShip                     (TCM_PROTECTED_ORDINAL + 0x0D)
// #define TCM_ORD_ChangeAuthOwner                (TCM_PROTECTED_ORDINAL + 0x10)
// #define TCM_ORD_Extend                                   (TCM_PROTECTED_ORDINAL + 0x14)
 #define TCM_ORD_PCRRead                               (TCM_PROTECTED_ORDINAL + 0x15)
// #define TCM_ORD_Quote                                     (TCM_PROTECTED_ORDINAL + 0x16)
// #define TCM_ORD_Seal						(TCM_PROTECTED_ORDINAL+0x17)
// #define TCM_ORD_Unseal   					(TCM_PROTECTED_ORDINAL+0x18)
// #define TCM_ORD_CreateWrapKey                     (TCM_PROTECTED_ORDINAL + 0x1F)
 #define TCM_ORD_GetPubKey					(TCM_PROTECTED_ORDINAL + 0x21)
// #define	TCM_ORD_CertifyKey							 (TCM_PROTECTED_ORDINAL + 0x32)
// #define TCM_ORD_Sign 						(TCM_PROTECTED_ORDINAL + 0x3c)
// #define TCM_ORD_SetCapability				 (TCM_PROTECTED_ORDINAL + 0x3F)
// #define TCM_ORD_GetRandom                           (TCM_PROTECTED_ORDINAL + 0x46)
// #define TCM_ORD_SelfTestFull				 (TCM_PROTECTED_ORDINAL + 0x50)
// #define TCM_ORD_ContinueSelfTest			 (TCM_PROTECTED_ORDINAL + 0x53)
// #define TCM_ORD_GetTestResult				 (TCM_PROTECTED_ORDINAL + 0x54)
// #define TCM_ORD_OwnerClear                           (TCM_PROTECTED_ORDINAL + 0x5B)
// #define TCM_ORD_DisableOwnerClear                (TCM_PROTECTED_ORDINAL+ 0x5C)
// #define TCM_ORD_ForceClear 	 				(TCM_PROTECTED_ORDINAL+0x5D)
// #define TCM_ORD_DisableForceClear                 (TCM_PROTECTED_ORDINAL + 0x5E)
// #define TCM_ORD_GetCapability				 (TCM_PROTECTED_ORDINAL + 0x65)
// #define TCM_ORD_OwnerSetDisable                    (TCM_PROTECTED_ORDINAL+0x6E)
// #define TCM_ORD_PhysicalEnable                       (TCM_PROTECTED_ORDINAL+0x6F)
// #define TCM_ORD_PhysicalDisable                       (TCM_PROTECTED_ORDINAL+0x70)
// #define TCM_ORD_SetOwnerInstall                       (TCM_PROTECTED_ORDINAL+0x71)
// #define TCM_ORD_PhysicalSetDeactivated           (TCM_PROTECTED_ORDINAL+0x72)
// #define TCM_ORD_SetTempDeactivated               (TCM_PROTECTED_ORDINAL+0x73)
// #define TCM_ORD_SetOperatorAuth                     (TCM_PROTECTED_ORDINAL+0x74)
// #define TCM_ORD_CreateEndorsementKeyPair    (TCM_PROTECTED_ORDINAL+0x78)
// #define TCM_ORD_MakeIdentity 				(TCM_PROTECTED_ORDINAL+0x79)
// #define TCM_ORD_ActivateIdentity				(TCM_PROTECTED_ORDINAL+0x7A)
 #define TCM_ORD_ReadPubEK                             (TCM_PROTECTED_ORDINAL+0x7C)
// #define TCM_ORD_CreateRevocableEK                (TCM_PROTECTED_ORDINAL+0x7F)
// #define TCM_ORD_RevokeTrust                            (TCM_PROTECTED_ORDINAL+0x80)
// #define TCM_ORD_OwnerReadInternalPub          (TCM_PROTECTED_ORDINAL+0x81)
// #define TCM_ORD_GetAuditDigest				(TCM_PROTECTED_ORDINAL+0x85)
// #define TCM_ORD_GetAuditDigestSigned		(TCM_PROTECTED_ORDINAL+0x86)
// #define TCM_ORD_SetOrdinalAuditStatus		(TCM_PROTECTED_ORDINAL+0x8D)
// #define TCM_ORD_SaveState                             (TCM_PROTECTED_ORDINAL + 0x98)
// #define TCM_ORD_Startup                                  (TCM_PROTECTED_ORDINAL + 0x99)
// #define TCM_ORD_SaveContext                         (TCM_PROTECTED_ORDINAL + 0xB8)
// #define TCM_ORD_LoadContext                         (TCM_PROTECTED_ORDINAL + 0xB9)
// #define TCM_ORD_FlushSpecific                        (TCM_PROTECTED_ORDINAL + 0xBA)
// #define TCM_ORD_APCreate                                (TCM_PROTECTED_ORDINAL+0xBF)
// #define TCM_ORD_APTerminate                          (TCM_PROTECTED_ORDINAL+0xC0)
// #define TCM_ORD_CreateMigratedBlob               (TCM_PROTECTED_ORDINAL+0xC1)
 #define TCM_ORD_ConvertMigratedBlob               (TCM_PROTECTED_ORDINAL+0xC2)
// #define TCM_ORD_AuthorizeMigrationKey          (TCM_PROTECTED_ORDINAL+0xC3)
// #define TCM_ORD_SMS4Encrypt                        (TCM_PROTECTED_ORDINAL + 0xC5)
// #define TCM_ORD_SMS4Decrypt                        (TCM_PROTECTED_ORDINAL + 0xC6)
// #define TCM_ORD_PCR_Reset                              (TCM_PROTECTED_ORDINAL+0xC8)
// #define TCM_ORD_NV_DefineSpace                     (TCM_PROTECTED_ORDINAL+0xCC)
// #define TCM_ORD_NV_WriteValue                       (TCM_PROTECTED_ORDINAL+0xCD)
// #define TCM_ORD_NV_WriteValueAuth                (TCM_PROTECTED_ORDINAL+0xCE)
// #define TCM_ORD_NV_ReadValue                        (TCM_PROTECTED_ORDINAL+0xCF)
// #define TCM_ORD_NV_ReadValueAuth                 (TCM_PROTECTED_ORDINAL+0xD0)
// #define TCM_ORD_ActivatePEK 				(TCM_PROTECTED_ORDINAL+0xD9)
// #define TCM_ORD_ActivatePEKCert			 (TCM_PROTECTED_ORDINAL+0xDA)
// #define TCM_ORD_CreateCounter 				(TCM_PROTECTED_ORDINAL+0xDC)
// #define TCM_ORD_IncrementCounter 			(TCM_PROTECTED_ORDINAL+0xDD)
// #define TCM_ORD_ReadCounter  				(TCM_PROTECTED_ORDINAL+0xDE)
// #define TCM_ORD_ReleaseCounter 			(TCM_PROTECTED_ORDINAL+0xDF)
// #define TCM_ORD_ReleaseCounterOwner           (TCM_PROTECTED_ORDINAL+0xE0)
// #define TCM_ORD_SM3Start                                (TCM_PROTECTED_ORDINAL + 0xEA)
// #define TCM_ORD_SM3Update                            (TCM_PROTECTED_ORDINAL + 0xEB)
// #define TCM_ORD_SM3Complete                        (TCM_PROTECTED_ORDINAL + 0xEC)
// #define TCM_ORD_SM3CompleteExtend               (TCM_PROTECTED_ORDINAL+0xED)
// #define TCM_ORD_SM2Decrypt                           (TCM_PROTECTED_ORDINAL + 0xEE)
// #define TCM_ORD_LoadKey                                  (TCM_PROTECTED_ORDINAL+0xEF)
// #define TCM_ORD_GetTicks                                 (TCM_PROTECTED_ORDINAL+0xF1)
// #define TCM_ORD_TickStampBlob				(TCM_PROTECTED_ORDINAL+0xF2)
// #define TCM_ORD_GetResponseData                   (TCM_PROTECTED_ORDINAL+0xF00)
// 
// #define TCM_ORD_CertifyKey (TCM_PROTECTED_ORDINAL + 0x32)
 #define TCM_ORD_CertifyKey2 	(TCM_PROTECTED_ORDINAL + 0x33)
 #define TCM_ORD_EstablishTransport 	(TCM_PROTECTED_ORDINAL + 0xE6)
 #define TCM_ORD_ExecuteTransport 	(TCM_PROTECTED_ORDINAL + 0xE7)
// #define TCM_ORD_FieldUpgrade 	(TCM_PROTECTED_ORDINAL + 0xAA)
 #define TCM_ORD_Quote2 	(TCM_PROTECTED_ORDINAL + 0x3E)
 #define TCM_ORD_ReleaseTransportSigned 	(TCM_PROTECTED_ORDINAL + 0xE8)
// #define TCM_ORD_ResetLockValue 	(TCM_PROTECTED_ORDINAL + 0x40)
 #define TCM_ORD_Sealx 	(TCM_PROTECTED_ORDINAL + 0x3D)
// #define TSC_ORD_ResetEstablishmentBit 	(TCM_PROTECTED_ORDINAL + 0x0B)
 #define TCM_ORD_WrapKey   	(TCM_PROTECTED_ORDINAL + 0xBD)
 #define TCM_ORD_ReadEKCert 	(TCM_PROTECTED_ORDINAL + 0xC7)
 #define TCM_ORD_WriteEKCert 	(TCM_PROTECTED_ORDINAL + 0xE9)
 #define TCM_ORD_ReleaseSM2ExchangeSession 	(TCM_PROTECTED_ORDINAL + 0xAE)
 #define TCM_ORD_CreateSM2ExchangeSession 	(TCM_PROTECTED_ORDINAL + 0xAF)
 #define TCM_ORD_GetKeySM2ExchangeSession 	(TCM_PROTECTED_ORDINAL + 0xB0)
// 
// #define TCM_ORD_JW_SendCmd7816			(TCM_PROTECTED_ORDINAL+0x600)
// #define TCM_ORD_JW_GetRTC			(TCM_PROTECTED_ORDINAL+0x601)
// #define TCM_ORD_JW_CheckRTC			(TCM_PROTECTED_ORDINAL+0x611)
// #define	TCM_ORD_JW_MainAuth			(TCM_PROTECTED_ORDINAL+0x602)
// #define	TCM_ORD_JW_WarmRst7816			(TCM_PROTECTED_ORDINAL+0x603)
// #define	TCM_ORD_JW_GetUserList			(TCM_PROTECTED_ORDINAL+0x606)
// #define	TCM_ORD_JW_GetAllUserList		(TCM_PROTECTED_ORDINAL+0x616)
// #define	TCM_ORD_JW_PutUserList			(TCM_PROTECTED_ORDINAL+0x607)
// #define	TCM_ORD_JW_PutAllUserList		(TCM_PROTECTED_ORDINAL+0x617)
// #define	TCM_ORD_JW_GetUserInfo			(TCM_PROTECTED_ORDINAL+0x608)
// #define	TCM_ORD_JW_EjectCard7816		(TCM_PROTECTED_ORDINAL+0x604)
// #define	TCM_ORD_JW_LockDevice			(TCM_PROTECTED_ORDINAL+0x605)
// 
// #define TCM_ORD_JW_ReadSSA 			(TCM_PROTECTED_ORDINAL+0x6f1)
// #define TCM_ORD_JW_WriteSSA 			(TCM_PROTECTED_ORDINAL+0x6f2)




#pragma pack(pop)

#endif
