//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by tycspi.rc
//
#define IDC_READER_LIST                 1002
#define IDC_CARD_NAME                   1006
#define IDC_CARD_STATUS                 1008
#define IDC_REFRESH                     1009
#define IDD_OPENCARD                    1011
#define IDI_CARD_UNAVAIL                1012
#define IDI_CARD_NO                     1013
#define IDI_CARD_HAVE                   1014
#define IDI_READER_UNKNOWN              1015

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
